total_steps: 16
img_savepoint: 4
learning_rate: 0.001
content_weight: 1
style_weight: 0.1
path: "generated.png"
imsize: 356
style_images: # Keep this in list format, even if one image
  - "dali.jpg"
  - "burning_forest.jpg"
content_image: "lab.jpg"

# Complex model 2 only
style_loss_type: "GRAM"