wandb_version: 1

total_steps:
  desc: null
  value: 25
learning_rate:
  desc: null
  value: 0.001
alpha:
  desc: null
  value: 1
beta:
  desc: null
  value: 0.01
_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.17.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1723146770
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.11.4
      5: 0.17.6
      8:
      - 5
      13: linux-x86_64
