wandb_version: 1

total_steps:
  desc: null
  value: 500
learning_rate:
  desc: null
  value: 0.001
alpha:
  desc: null
  value: 1
beta:
  desc: null
  value: 0.01
imsize:
  desc: null
  value: 356
_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.17.0
    framework: huggingface
    huggingface_version: 4.29.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1723158736
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      3:
      - 16
      - 23
      4: 3.11.4
      5: 0.17.0
      6: 4.29.2
      8:
      - 5
      13: linux-x86_64
